#!/usr/bin/perl -w

use strict;
use blib;
use XML::Xalan;

die <<"USAGE" if @ARGV < 2;
Usage: $0 xml_file xsl_file [out_file]
USAGE

my $tr = new XML::Xalan::Transformer;

if (@ARGV > 2) {
    $tr->transform_to_file(@ARGV) 
        or die $tr->errstr;
} else {
    my $res = $tr->transform_to_data(@ARGV);
    if (defined $res) { 
        print $res;
    } else { 
        die $tr->errstr;
    }
}
